version: 2.1
workflows:
  test_deploy:
    jobs:
      - python_setup

jobs:
  python_setup:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - run:
          name: Install Requirements
          command: pip install -r requirement.txt
      - run:
          name: Install Numpy
          command: pip install numpy